spring.application.name=ssia
spring.datasource.url=jdbc:mysql://localhost/ssia
spring.datasource.username=ssiauser
spring.datasource.password=ssiapass
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always